export const cities = [
    "Casablanca",
    "Rabat",
    "Fes",
    "Marrakech",
    "Agadir",
    "Tangier",
    "Meknes",
    "Oujda",
    "Kenitra",
    "Tetouan",
    "Safi",
    "Khouribga",
    "El Jadida",
    "Beni Mellal",
    "Ait Melloul",
    "Nador",
    "Taza",
    "Settat",
    "Berrechid",
    "Khemisset",
    "Inezgane",
    "Ksar El Kebir",
    "Larache",
    "Guelmim",
    "Khenifra",
    "Berkane",
    "Taourirt",
    "Bouskoura",
    "Fquih Ben Salah",
    "Dcheira El Jihadia",
    "Oued Zem",
    "Sidi Slimane",
    "Errachidia",
    "Guercif",
    "Oulad Teima",
    "Ben Guerir",
    "Sidi Kacem",
    "Tiflet",
    "Essaouira",
    "Taroudant",
    "Ouarzazate",
    "Lqliaa",
    "Sidi Bennour",
    "Al Hoceima",
    "Youssoufia",
    "Martil",
    "Ain Harrouda",
    "Dakhla",
    "Sefrou",
    "Mohammedia",
    "Skhirat",
    "Souk El Arbaa",
    "Fnideq",
    "Azrou",
    "Ait Ourir",
    "Ain El Aouda",
    "Temara",
    "Midelt",
    "Sidi Ifni",
    "Zagora",
    "Jerada",
    "Azemmour",
    "Bouznika",
    "El Hajeb",
    "Tiznit",
    "Tan-Tan",
    "Sidi Yahya El Gharb",
    "Ain Taoujdate",
    "Ait Baha",
    "Ait Melloul",
    "Ait Ourir",
    "Al Hoceima",
    "Asilah",
    "Azilal",
    "Azrou",
    "Ben Ahmed",
    "Ben Guerir",
    "Beni Ansar",
    "Beni Mellal",
    "Berkane",
    "Berrechid",
    "Bouarfa",
    "Boujdour",
    "Boulemane",
    "Bouznika",
    "Casablanca",
    "Chefchaouen",
    "Chichaoua",
    "Dakhla",
    "Demnate",
    "Driouch",
    "El Hajeb",
    "El Jadida",
    "El Kelaa des Sraghna",
    "Errachidia",
    "Essaouira",
    "Fes",
    "Figuig",
    "Fnideq",
    "Fquih Ben Salah",
    "Guelmim",
    "Guercif",
    "Ifrane",
    "Inezgane",
    "Jerada",
    "Kelaat Sraghna",
    "Kénitra",
    "Khemisset",
    "Khenifra",
    "Khouribga",
    "Ksar El Kebir",
    "Laayoune",
    "Larache",
    "Marrakech",
    "Martil",
    "Meknes",
    "Midelt",
    "Mohammedia",
    "Nador",
    "Ouarzazate",
    "Oued Zem",
    "Oujda",
    "Rabat",
    "Safi",
    "Salé",
    "Sefrou",
    "Settat",
    "Sidi Bennour",
    "Sidi Ifni",
    "Sidi Kacem",
    "Sidi Slimane",
    "Skhirat",
    "Souk El Arbaa",
    "Tanger",
    "Tan-Tan",
    "Taourirt",
    "Tarfaya",
    "Taroudant",
    "Taza",
    "Temara",
    "Tiflet",
    "Tinghir",
    "Tiznit",
    "Youssoufia",
    "Zagora",
  ];
  export const offices = [
    "DirhamX",
    "Golden Dirham",
    "Rabat exchange",
    "Casaforex",
    "Oasis Currency",
    "Central Atlas Exchange",
  ];
  